#!/bin/sh
set -e # exit on an error
do_info_jsonl(){
    echo '{"API":"v0"}'
}
do_enum_jsonl(){
    for f in $(seq 1 10); do
	echo "{\"Command\": \"sleep $f\"}"
    done
}
do_exec(){
    $@
}
case "$1" in
    "info-jsonl" ) do_info_jsonl;;
    "enum-jsonl" ) do_enum_jsonl;;
    "exec" ) shift; do_exec "$@";;
    * ) echo "Usage: $(basename $0) info-jsonl | enum-jsonl | exec [COMMAND]" >&2 ; exit 1;;
esac
